### ISSUE TITLE
Failed to Install - Mac OSX

### ISSUE THREAD

**Issue by AndrewZurn** [sindresorhus/infer-bin#1]
I'm having some issues installing the library.  Hopefully this isn't just a user error, as I'm not to versed with Node or npm.

<pre>
> thread-sleep@1.0.3 install /Users/andrew/bin/nodejs/lib/node_modules/infer-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep
> node-pre-gyp install --fallback-to-build

[thread-sleep] Success: "/Users/andrew/bin/nodejs/lib/node_modules/infer-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/lib/binding/Release/node-v11-darwin-x64/thread_sleep.node" is installed via remote

> spawn-sync@1.0.11 postinstall /Users/andrew/bin/nodejs/lib/node_modules/infer-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

/Users/andrew/bin/nodejs/bin/infer -> /Users/andrew/bin/nodejs/lib/node_modules/infer-bin/cli.js

> infer-bin@0.1.1 postinstall /Users/andrew/bin/nodejs/lib/node_modules/infer-bin
> node lib/install.js

/Users/andrew/bin/nodejs/lib/node_modules/infer-bin/lib/index.js:36
                throw err;
                      ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

npm ERR! infer-bin@0.1.1 postinstall: `node lib/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the infer-bin@0.1.1 postinstall script.
npm ERR! This is most likely a problem with the infer-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls infer-bin
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.4.0
npm ERR! command "/Users/andrew/bin/nodejs/bin/node" "/Users/andrew/bin/nodejs/bin/npm" "install" "--global" "infer-bin"
npm ERR! cwd /Users/andrew/work/consensus/Consensus/Reports/Infer
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
</pre>

**Comment by kevva** [comment]
Could you try updating npm (and maybe node)? Just run `npm install --global npm@3`.

**Comment by arthurvr** [comment]
This seems reproducable on Travis atm.

**Comment by bw-yuhogg** [comment]
Fails on Linux too. And updating npm doesn't fix the problem.

**Comment by sindresorhus** [comment]
Fixed
